name: Docker Image CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: |
          flag=$(date +%s)
          echo ${ImageName}:${flag}
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.pkg.github.com -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build . --file Dockerfile --tag ${ImageName}:${flag}
          docker push ${ImageName}:${flag}
        env:
          ImageName: docker.pkg.github.com/ridgarou/docker-sample/docker-sample
