name: Docker Image CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: |
          echo ${ImageName}
          docker build . --file Dockerfile --tag ${ImageName}
          docker push ${ImageName}
        env:
          ImageName: $("docker.pkg.github.com/ridgarou/docker-sample/docker-sample:$(date +%s)")
