name: Docker Image CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: |
          echo "${ImageName}:${Flag}"
          docker build . --file Dockerfile --tag "${ImageName}:${Flag}"
          docker push "${ImageName}:${Flag}"
        env:
          ImageName: docker.pkg.github.com/ridgarou/docker-sample/docker-sample
          Flag: $(date +%s)
