name: Docker Image CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1       
      - name: Buildx the Docker image
        run: |
          flag=$(date +%s)
          echo "*** Imagen a crear ${DOCKER_REGISTRY_URL}/${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${flag}"
          echo "*** Login en ${DOCKER_REGISTRY_URL}"
          echo "${DOCKER_PASSWORD}" | docker login ${DOCKER_REGISTRY_URL} -u "${DOCKER_USERNAME}" --password-stdin
          echo "*** Construimos la imagen ${DOCKER_IMAGE_NAME}:latest"
          sudo docker buildx build . \
            --platform linux/arm64 \
            --file Dockerfile \
            --tag ${DOCKER_IMAGE_NAME}:latest \
            --tag ${DOCKER_IMAGE_NAME}:${flag} \
            --output "type=image,push=false"
          sudo docker tag ${DOCKER_IMAGE_NAME}:latest ${DOCKER_REGISTRY_URL}/${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest
          sudo docker push ${DOCKER_REGISTRY_URL}/${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest
          #echo "*** Construimos la imagen ${DOCKER_IMAGE_NAME}:latest"
          #sudo docker buildx build . \
          #  --platform linux/arm64 \
          #  --file Dockerfile \
          #  --tag ${DOCKER_IMAGE_NAME}:latest \
          #  --tag ${DOCKER_IMAGE_NAME}:${flag} 
          #  #--output "type=image,push=false"
          #sudo docker tag ${DOCKER_IMAGE_NAME}:latest ${DOCKER_REGISTRY_URL}/${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${flag}
          #sudo docker image ls
          #echo "*** Login en ${DOCKER_REGISTRY_URL}"
          #echo "${DOCKER_PASSWORD}" | docker login ${DOCKER_REGISTRY_URL} -u "${DOCKER_USERNAME}" --password-stdin
          #echo "*** Publicamos la imagen ${DOCKER_REGISTRY_URL}/${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${flag}"
          #sudo docker push "${DOCKER_REGISTRY_URL}/${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${flag}"
        env:
          #DOCKER_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          #DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          #DOCKER_REGISTRY_URL: docker.pkg.github.com:  
          DOCKER_USERNAME: ridgarou
          DOCKER_PASSWORD: Reaper01
          DOCKER_REGISTRY_URL: docker.io
          DOCKER_IMAGE_NAME: docker-sample
