name: Docker Image CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: |
          flag=$(date +%s)
          echo "${ImageName}:${flag}"
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u "${{ secrets.GITHUB_USERNAME }}" --password-stdin
          docker build . --file Dockerfile --tag "${ImageName}:${flag}"
          docker push "${ImageName}:${flag}"
        env:
          ImageName: docker.pkg.github.com/ridgarou/docker-sample/docker-sample
