name: Docker Image CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Buildx the Docker image
        run: |
          flag=$(date +%s)
          echo "${ImageName}:${flag}"
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u "${{ secrets.GITHUB_USERNAME }}" --password-stdin
          #docker build . --file Dockerfile --tag "${ImageName}:${flag}"
          docker buildx build \
            --platform linux/arm64 \
            --output "type=image,push=false" \
            --file ./Dockerfile \
            --tag "${ImageName}:${flag}"
          docker push "${ImageName}:${flag}"
        env:
          ImageName: docker.pkg.github.com/ridgarou/docker-sample/docker-sample
