name: Docker Image CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: |
          echo ${ImageName}:${Tag}
          docker build . --file Dockerfile --tag ${ImageName}:${Tag}
          docker push ${ImageName}:${Tag}
        env:
          ImageName: docker.pkg.github.com/ridgarou/docker-sample/docker-sample
          Tag: $(date +%s)
