name: Docker Image CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Buildx the Docker image
        run: |
          flag=$(date +%s)
          echo "*** Imagen a crear ${ImageName}:${flag}"
          echo "*** Login en docker.pkg.github.com"
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u "${{ secrets.GITHUB_USERNAME }}" --password-stdin
          #echo "*** Limpiamos la cache"
          #docker builder prune -af
          echo "*** Construimos la imagen"
          docker buildx build . \
            --platform linux/arm64 \
            --output type=registry \
            --file Dockerfile \
            --tag "${ImageName}:${flag}"
          #echo "*** Publicamos la imagen"
          #docker push "${ImageName}:${flag}"
        env:
          ImageName: docker.pkg.github.com/ridgarou/docker-sample/docker-sample
